### ISSUE TITLE
Textbox background missing in OS X

### ISSUE THREAD

**Issue by rosshettel** [robertlugg/easygui#125]
<img width="461" alt="screen_shot_2017-03-27_at_4 03 15_pm" src="https://cloud.githubusercontent.com/assets/773995/25091794/7b88a054-2350-11e7-8d52-5e3bd8fb2d9f.png">

When building for OS X, the textbox and other UI elements are not visible. This does not happen for Windows and Linux.

**Comment by spyoungtech** [comment]
Can you provide some system information and minimal steps to reproduce this issue? Are you running the latest version? I don't think I've run into this issue before on El Capitan or Sierra, but will do some testing if you can provide those details.
