### ISSUE TITLE
apt-get install python-easygui installs old version of easygui

### ISSUE THREAD

**Issue by m-Linus** [robertlugg/easygui#133]
I have installed easygui with apt-get install python-easygui.
Unfortunately, it is only version 0.96 (2010-08-29).
Do you have any influence on what package is installed with apt-get and, if yes, would you update it?

**Comment by spyoungtech** [comment]
I imagine that is the Stephen Ferg version. @robertlugg would probably know best if it's possible/practical to do this.

Although, if you need the later versions, is there an issue with getting them via `pip` ?

**Comment by zadacka** [comment]
APT has included 0.96-3 for some time (see the [last few Debian releases](https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=sourcenames&keywords=python-easygui)). I/we don't have control over what goes into APT - but I have contacted the relevant mailing list and asked whether it would be feasible to get the version updated to the current PIP version. 

In the meantime, @spyoungtech 's suggestion of using 'pip' will be your fastest and easiest way forward.

Does that all sound okay?

**Comment by m-Linus** [comment]
I'll tty this as soon as possible. Thank you for the answer.
