### ISSUE TITLE
easygui 98 error on Python - can't import tkinter

### ISSUE THREAD

**Issue by hamdyaea** [robertlugg/easygui#134]
I try to launch my python program then I have this error : 

Traceback (most recent call last):
  File "multiquestions-scrum-quiz.py", line 26, in <module>
    game_start = buttonbox(title=start_title,image=logo,msg=start_msg,choices=play)
  File "/usr/lib/python3.6/site-packages/easygui/boxes/button_box.py", line 102, in buttonbox
    callback=callback)
  File "/usr/lib/python3.6/site-packages/easygui/boxes/button_box.py", line 147, in __init__
    self.ui = GUItk(msg, title, choices, images, default_choice, cancel_choice, self.callback_ui)
  File "/usr/lib/python3.6/site-packages/easygui/boxes/button_box.py", line 263, in __init__
    self.boxRoot = tk.Tk()
  File "/usr/lib/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: unknown color name "BACKGROUND"

**Comment by zadacka** [comment]
What Operating System are you using? If you are using Debian, could you try the steps outlined [here](https://www.q4os.org/forum/viewtopic.php?id=910):
```
$ xrdb -load /dev/null
$ xrdb -query
```

I don't think that this is an EasyGui bug, but rather a problem with getting default values for Tk GUI elements. If the above fails we can try [an alternative approach to setting defaults](https://soulkiln.blog/2014/07/19/pysolfc-on-centos-7-tk-errors/).

**Comment by hamdyaea** [comment]
I'm using archlinux and my Python is installed from Arch-Anywhere. After recompilation of python36 and a reboot everything works.

The problem is solved.

**Comment by zadacka** [comment]
Excellent! Thanks for sharing details, and that the problem is now resolved.
