### ISSUE TITLE
easygui seems to require "Tk" but the readme says otherwise

### ISSUE THREAD

**Issue by hilbrichtsoftware** [robertlugg/easygui#135]
Hello,

I wanted to try out easygui for the very reason that you write  "and does not have any dependencies beyond python." However, looking into the code it says in the documentation that is requires Tk and indeed, after uninstalling Tk it does not work anymore.

I ask you to change the summary description that easygui is indeed a convenience script for Tk and therefore has Tk as dependency, besides python.

**Comment by zadacka** [comment]
That's a reasonable update to make. easygui can/could be used with other windowing libraries, but by default it is intended to be used with Tk, and we should say as much in the summary.

I've amended the README.txt and README.md in line with this.
