### ISSUE TITLE
choicebox non supported on Mac OS X

### ISSUE THREAD

**Issue by gustavohmsilva** [robertlugg/easygui#137]
I experienced problems with a little script with GUI I've created. Since it originally worked when it was just on terminal, I was attempting to try to see that code caused a segmentation fault 11 on my code, and I discovered that the function choicebox() is completely unsupported on Mac OS X.

**Comment by zadacka** [comment]
That's strange - I've just tried running the choicebox on a mac and it worked fine. Could you try:
```
from easygui.boxes import demo
demo.demo_choicebox()
```

**Comment by gustavohmsilva** [comment]
Hi @zadacka. I have completely no idea what happened. I've  installed easygui on another Mac OS X with the same setup and everything worked fine this time. The only difference I can see between them is that one machine had python installed over homebrew, the other, the DMG installer were downloaded from the Python website.

**Comment by zadacka** [comment]
Ah, glad to hear that you're up and running again! Thanks for the context - if this affects other users we can investigate further and that may prove to be useful information.
