### ISSUE TITLE
what is process of deploying easygui application?

### ISSUE THREAD

**Issue by sirish49** [robertlugg/easygui#138]
can we deploy 'easygui' application? If so, how? I have done a simple easy GUI application using Python 3.6 Now I want to create a setup file for the same.

**Comment by zadacka** [comment]
You can certainly deploy an application developed that uses easygui!

How you do so very much depends on the type of application/deployment you want to do. One of the standard ways to do this would be to use [setuptools](https://setuptools.readthedocs.io/en/latest/setuptools.html). Specifically you may want to consider building a [wheel](https://packaging.python.org/tutorials/distributing-packages/#wheels) for distribution. You can then copy the wheel across to the target system and use `easy_gui` to install it (presuming that you have a python installation on the target system already).

Easygui is available through the Python Package Index (PyPi) so you can specify it as a required dependency in your setup.py, and do not need to manually include any easygui files.

If you're reading around on this, it is worth noting that there are a *lot* of ways of doing deployment. 
Within the python world, `setuptools` is the successor to `distutils`, and the `wheel` packaging system is the successor to the `egg`. Wherever you see those terms you know that they are talking about the same sort of thing.

Hope this is useful! I'd suggest that you have a look into using `setuptools` to build a `wheel`, and let me know if you have further questions.
