### ISSUE TITLE
Not finding module/python 2.5.4

### ISSUE THREAD

**Issue by geekgamer2001** [robertlugg/easygui#141]
When I  do import easygui i get an error but I am sure it's in the path.

**Comment by zadacka** [comment]
Huh, that’s strange. How did you install easygui - using PIP/easy_insyall?

On Sat, Mar 24, 2018 at 23:09, geekgamer2001 <notifications@github.com> wrote:
When do import easygui i get an error but I am sure it's in the path.

**Comment by geekgamer2001** [comment]
um i went and downloaded the easygui-0.97.zip on sorce forge

**Comment by geekgamer2001** [comment]
I do have so many pythons on my computer that might be why. I am supposed to put the file in the python 2.5 file right?

**Comment by geekgamer2001** [comment]
The reason is that it's 2.7+
