### ISSUE TITLE
Is this project looking for maintainers?

### ISSUE THREAD

**Issue by spyoungtech** [robertlugg/easygui#154]
Would be happy to contribute in this capacity.

**Comment by zadacka** [comment]
Hi @spyoungtech! Sure - I think that we're always going to welcome help. What are you particularly interested in doing? Message me directly, if you like.

**Comment by spyoungtech** [comment]
This project has always had my interest, as it helped me be productive in creating usable solutions at my job, and was one of my first steps into open source contributions, actually thanks to Stephen Ferg. So, at any rate, I'd be happy to give back when and where I can.

There's a couple things on my mind that I'd be happy to tackle as a collaborator

* Resolving/managing outstanding issues/PRs
* Getting some CI setup

  * Run tests and build wheels automatically. Probably want to convert the current `test_cases` to proper unittests and/or write new tests altogether too.
  * Coverage
  * Maybe automated PyPI/SourceForge deployments on tagged commits to master
  * Maybe capture screenshots as artifacts for visual verification of changes

* Driving fixes/changes and new releases in general


Other than that, I think some other things I have in mind could be addressed as separate issues, but might include some larger undertakings like

* Refactor to reduce code/duplication (particularly around `GUItk` classes used in a few boxes)
* Improving style, (esp noticeable on modern Windows systems), by leveraging tkinter themed widgets (e.g. `ttk`) for a native look/feel. 
* Additional Features/widgets, maybe similar to what you might find in [PySimpleGui](https://github.com/PySimpleGUI/PySimpleGUI)

**Comment by zadacka** [comment]
Sounds good!

You are 100% correct that we've got a need to address some issues, and add some improvements. And, as you can probably surmise from the slow response, I think that the project will also welcome active collaborators to address said issues.

I've got a branch set up that uses Travis CI and some tests to start working towards coverage, but my attempts thus far to DRY out the code and implement other backwards-compatible cleanups has been glacier slow. Have a look at my fork of the repo to see work-in-progress (though I wouldn't recommend basing any work on it, as I'm planning to treat that branch as a spike and throw away / re-package the majority of those changes as more meaningful commits).

In general, all pull requests to address issues are welcome, as well as broader improvements. Also, very open to discussion on change priority / updates to the project.

Warm regards,
Alex
