### ISSUE TITLE
TclError: bad screen distance "4.5i"

### ISSUE THREAD

**Issue by pgr123** [robertlugg/easygui#169]
I would try multenterbox but I got an error and I think that error is because I am french and it would be 4,5i and not 4.5i, Is that true ? How solve that problem ?
Easygui is very great and it is a pity that that does not work.
I hope there is a solution.
I use Ubuntu 18.04 64bits and easygui 0.98.1.
Thank you.
Excuse my bad english.
Pascal

**Comment by spyoungtech** [comment]
Could you provide code that can be used to reproduce this problem?

**Comment by pgr123** [comment]
Thank you very much but it seems that now all works fine (Maybe an update of Ubuntu mate made the work). 
So, I close that error and I hope that it does not come back on day. 
Thank you. Have a good day.
Pascal

**Comment by brazoayeye** [comment]
Same problem here. Staks says occurance is on 

```
  File "venv\Lib\site-packages\easygui\boxes\derived_boxes.py", line 361, in enterbox
    result = __fillablebox(
             ^^^^^^^^^^^^^^
  File "venv\Lib\site-packages\easygui\boxes\fillable_box.py", line 90, in __fillablebox
    messageWidget = tk.Message(messageFrame, width="4.5i", text=msg)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\tkinter\__init__.py", line 3474, in __init__
    Widget.__init__(self, master, 'message', cnf, kw)
  File "C:\Program Files\Python311\Lib\tkinter\__init__.py", line 2628, in __init__
    self.tk.call(
_tkinter.TclError: bad screen distance "4.5i"
```
