### ISSUE TITLE
Importing ABC directly from collections has been deprecated and will be removed in Python 3.10

### ISSUE THREAD

**Issue by tirkarthi** [robertlugg/easygui#172]
Use collections.abc for Python 3 and collections for Python 2.

```
easygui/boxes/choice_box.py
72:    if not isinstance(obj, collections.Sequence):
```

**Comment by ASobrino** [comment]
Now this is happening with Python 3.10

**Comment by tirkarthi** [comment]
I will create a PR

**Comment by tirkarthi** [comment]
Looks like this is fixed in https://github.com/tirkarthi/easygui/commit/0f6abd5b37c8295618412f9ea38aa7da5d3d87af#diff-fef111e52e6c8332a082cc8d35153b1057c8f3c92e75d59d8be4a82051417195 . Closing.

**Comment by tirkarthi** [comment]
Sorry, https://github.com/robertlugg/easygui/commit/652134c814e57b4c523683f77f97803d6d8e3b0c

**Comment by zadacka** [comment]
Yep - sorry, should have seen your previous open issue.

The collections movement got back ported for quite a few Python 3 versions for compatibility, so we got away with the old import location for a while!

Thanks for raising, investigating, and closing this out with information 👍

**Comment by Joeri-G** [comment]
It looks like this patch has not yet been pushed to the pypi repository. I encountered this issue when running my scripts on a different PC, which resulted in the classic "well it works on my machine" and was hot-fixed by downgrading the python install.

**Comment by toccata10** [comment]
Same here: pip install easygui doesn't install the corrected collections.abc version: it's still the old version.
