### ISSUE TITLE
Failed compile

### ISSUE THREAD

**Issue by kuboosoft** [robertlugg/easygui#33]
I tried compile for some distributions linux, but fail.

Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    import easygui
  File "/home/david/Downloads/python-easygui/src/easygui/easygui/__init__.py", line 3, in <module>
    __all__ = easygui.__all__
NameError: name 'easygui' is not defined

**Comment by rienafairefr** [comment]
Having the same issue on a win 7 installation. Using pip install does the same.

**Comment by rienafairefr** [comment]
I recommend close, saw your comment on sourceforge http://sourceforge.net/p/easygui/bugs/15/#3026 which addresses this issue.

**Comment by robertlugg** [comment]
thanks.  i decided to create a new build and upload 0.97.4  I hope this will now work out-of-the-box
