### ISSUE TITLE
windows 7 x64 / python 3.4 amd64 issue 

### ISSUE THREAD

**Issue by dirkpetersen** [robertlugg/easygui#50]
>python
Python 3.4.2 (v3.4.2:ab2c023a9432, Oct  6 2014, 22:16:31) [MSC v.1600 64 bit (AM
D64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import easygui
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\python\Python34\lib\site-packages\easygui\__init__.py", line 3, in <m
odule>
    __all__ = easygui.__all__
NameError: name 'easygui' is not defined
>>>

**Comment by robertlugg** [comment]
sorry for the trouble.  I believe you got unlucky and grabbed code when 'master' was broken.

I also see some additional trouble with importing easygui in python 3.4.2.  I'll take a look.

**Comment by robertlugg** [comment]
This was a problem when using python 3 with easygui.  Please grab the 0.97.4 package
