### ISSUE TITLE
get_string has duplicate window

### ISSUE THREAD

**Issue by stephenboulet** [robertlugg/easygui#66]
get_string has a duplicate window behind it that can be seen when the top dialog is moved.

from easygui_qt import *
from sys import exit

s = get_string('Enter a string')

print("String entered was %s" % s)
if s == "None":
    exit()
input()

When the top dialog is moved to the right, the other is visible behind it.

![easyguiqt](https://cloud.githubusercontent.com/assets/10341534/6561760/b47bfc1a-c661-11e4-9685-b79eeb3b6ece.png)

**Comment by stephenboulet** [comment]
Oh, easygui_qt 0.9.1 in Python 3.4.2 and PyQt GPL v4.11.3 on win7.

**Comment by robertlugg** [comment]
Hi Stephen, sorry for the delayed response.  This project is for a Tk version of easygui.  I believe you want the project at:
https://github.com/aroberge/easygui_qt

Best of luck.  I'll close this issue in a while if you don't.
