### ISSUE TITLE
Strange character is inserted in textbox when up or down arrow keys are pressed in Mac.

### ISSUE THREAD

**Issue by heemin32** [robertlugg/easygui#80]
In textbox, strage character() is inserted if I press up or down arrow keys in Mac.
![2015-09-04 5 46 18](https://cloud.githubusercontent.com/assets/1809492/9679826/e71a8d78-532c-11e5-90d6-a3ddea2b1e93.png)

**Comment by robertlugg** [comment]
Updated to 'develop' branch.  Can you check to see if still same problem?

**Comment by heemin32** [comment]
I can still see the same problem with the 'develop' branch.

**Comment by robertlugg** [comment]
I finally have a mac mini.  I'll see if I can confirm (and fix)
