### ISSUE TITLE
Move trash from master

### ISSUE THREAD

**Issue by BabyWolf** [robertlugg/easygui#82]
Please move all trash from master branch. To many trash on my hdd :  remove legacy_website/sourceforge_site_as_of_2014_11_21. Releases remove from master,  make it as branches.

**Comment by robertlugg** [comment]
Removed a couple.  I plan to integrate from develop into master shortly so may need to review again after that.

**Comment by robertlugg** [comment]
I believe I removed the unneeded/older files.  Thanks for writing this up
