### ISSUE TITLE
base_boxes : TypeError: 'dict_keys' object is not subscriptable

### ISSUE THREAD

**Issue by JanmanX** [robertlugg/easygui#84]
It seems there is invalid Python3 code in the base_boxes.py.
When creating a multchoicebox, Python crashes:

```
Traceback (most recent call last):
  File "scraper_gui.py", line 32, in <module>
  easygui.multchoicebox(msg = "Foo", title = "BAR", choices = l)
  File "/usr/local/lib/python3.4/dist-packages/easygui/boxes/derived_boxes.py", line 474, in multchoicebox
    return bb.__choicebox(msg, title, choices)
  File "/usr/local/lib/python3.4/dist-packages/easygui/boxes/base_boxes.py", line 428, in __choicebox
    choices = list(choices[:])
TypeError: 'dict_keys' object is not subscriptable
```

It seems this can be fixed by chaning the line 428 in base_boxes.py to:
```
choices = list(choices)
```
(Inspired by http://stackoverflow.com/questions/26394748/nltk-python-error-typeerror-dict-keys-object-is-not-subscriptable )

**Comment by robertlugg** [comment]
It is running properly now after the integration from develop to master.  Would you please validate and re-report if there is still an issue?  Thank you for reporting.
