### ISSUE TITLE
Fileopenbox Documentation Indicates Wrong Return value

### ISSUE THREAD

**Issue by jox58** [robertlugg/easygui#86]
The **fileopenbox** documentation on the [API page](http://easygui.sourceforge.net/api.html#easygui.fileopenbox) says "**Returns:** the name of a file, or *None if user chose to cancel*". However, if **Cancel** is selected the returned value is `'.'`
```
>>> easygui.fileopenbox(filetypes = ['*.csv','*.txt'])
'.'
```

**Comment by robertlugg** [comment]
confirmed, even on develop.

**Comment by robertlugg** [comment]
Fixed so now it returns None.
