### ISSUE TITLE
Unable to install easygui under Anaconda with Python 3.5 (on Windows)

### ISSUE THREAD

**Issue by nopria** [robertlugg/easygui#89]
I'd like to install easygui under an Anaconda environment using Conda, running the following commands in a command prompt:
```
anaconda search -t conda easygui
anaconda show achennu/easygui
conda install --channel https://conda.anaconda.org/achennu easygui
```

but I get the error:
```
Error: Unsatisfiable package specifications.
Generating hint:
[      COMPLETE      ]|##################################################| 100%

Hint: the following packages conflict with each other:
  - easygui
  - python 3.5*
```

Any chance to solve this issue?
Thanks.

**Comment by robertlugg** [comment]
This isn't a fix, but realize that easygui is just a set of python files.  You may download them from github and us them directly....there isn't much reason to install.

**Comment by nopria** [comment]
Great, I love code without installation. Thanks.

**Comment by nopria** [comment]
Anyway, maybe it's just a matter of adding an item like ```'Programming Language :: Python :: 3.5'```
to classifiers list in setup.py, or something simple like that.

**Comment by robertlugg** [comment]
OK I went ahead and added it.  note that a few lines above there is a '3' which I assumed actually covers all releases.
