### ISSUE TITLE
Multchoicebox: Disable preselect?

### ISSUE THREAD

**Issue by kieranjol** [robertlugg/easygui#92]
Hello Robert, 

Firstly thank you so much for making this program. 

It seems that `preselect=0 ` is enabled for the choiceboxes. I've found that this can cause an issue when there's a long list to choose from in a multchoicebox. As the first item is preselected, I've seen people just leaving it selected by mistake when clicking on numerous items. 
Is there any way to disable this aside from deleting instances of `preselect` in choice_box.py?

Thanks.

**Comment by TimOosterhoff** [comment]
Otherwise, in Multchoicebox `preselect `should be a List, so you can easily change the choices you did earlier.
But first to Robert: thanks!
Kind regards, Tim

**Comment by robertlugg** [comment]
I just checked in a change to support multiple values in preselect.  You may also set preselect to None and no entry is selected.  That will disable preselection.

Just to not take too much credit...I help to support easygui.  It was made by others mostly.  Glad it is useful to you.

**Comment by kieranjol** [comment]
Thank you!!

**Comment by kieranjol** [comment]
Apologies for the bump, but this fix has made my life so much easier. Thanks again!
